# infoware - C++ System information Library
#
# Written in 2017 by nabijaczleweli <nabijaczleweli@gmail.com> and ThePhD <phdofthehouse@gmail.com>
#
# To the extent possible under law, the author(s) have dedicated all copyright and related
# and neighboring rights to this software to the public domain worldwide. This software is
# distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along with this software.
# If not, see <http://creativecommons.org/publicdomain/zero/1.0/>

# wait for the day nab gets a GitHub sponsorship
#github: [ThePhD, nabijaczleweli]
patreon: nabijaczleweli
custom: https://www.paypal.me/nabijaczleweli
