set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR ${MINGW_ARCH})
set(MINGW_TOOLCHAIN ${MINGW_ARCH}-w64-mingw32)

set(CMAKE_FIND_ROOT_PATH /usr/${MINGW_TOOLCHAIN})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_C_COMPILER ${MINGW_TOOLCHAIN}-gcc)
set(CMAKE_CXX_COMPILER ${MINGW_TOOLCHAIN}-g++)
set(CMAKE_RC_COMPILER ${MINGW_TOOLCHAIN}-windres)
set(CMAKE_MC_COMPILER ${MINGW_TOOLCHAIN}-windmc)
